name: CI

on: [push]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: aquacash5/npm-gpr-auth@v2
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: npm install
      - run: npm publish