name: Publish package
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Choose the version type you want to publish
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch
  push:
    tags:
      - 'v*'
  release:
    types: [created]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container: node:24.17.0-bookworm@sha256:733e1c06ada118ed9f6133a31aa1290be6929664026fb28821500437c61f2c6f
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

  publish-to-gpr:
    name: Publish to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    container: node:24.17.0-bookworm@sha256:733e1c06ada118ed9f6133a31aa1290be6929664026fb28821500437c61f2c6f
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}

      - name: Bump version
        run: npm version --no-git-tag-version "${RELEASE_TYPE}"
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type || 'patch' }}

      - name: Publish to GPR
        run: |
          npm config set @fbuireu:registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken "${NODE_AUTH_TOKEN}"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-npm:
    name: Publish to npm Registry
    needs: build
    runs-on: ubuntu-latest
    container: node:24.17.0-bookworm@sha256:733e1c06ada118ed9f6133a31aa1290be6929664026fb28821500437c61f2c6f
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}

      - name: Bump version
        run: npm version --no-git-tag-version "${RELEASE_TYPE}"
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type || 'patch' }}

      - name: Publish to npm
        run: |
          npm config set @fbuireu:registry https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken "${NODE_AUTH_TOKEN}"
          npm publish --access=public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
